### ISSUE TITLE
Feature request: A method to check the availability of biometric auth

### ISSUE THREAD

**Issue by ExLuzZziVo** [FreakyAli/Plugin.Maui.Biometric#12]
Hi, Can you please add something like ```Task<bool> IsAvailableAsync``` method to the ```IBiometric``` interface to check the availability of biometric auth? It is useful for some android devices that doesn't have the fingerprint sensor or the biometric unlock is not set. Currently I check it like this:
```csharp
(await Plugin.Maui.Biometric.BiometricAuthenticationService.Default.GetEnrolledBiometricTypesAsync()).Count > 0
```

**Comment by FreakyAli** [comment]
Sure I will keep this in mind for the future

**Comment by FreakyAli** [comment]
@ExLuzZziVo Quick question why don't you do something to like: 

```
var biometric = BiometricAuthenticationService.Default;
var enrolledTypes = await biometric.GetEnrolledBiometricTypesAsync();
if(enrolledTypes != BiometricType.None)

```

**Comment by FreakyAli** [comment]
@ExLuzZziVo  Do you have any updates yet?

**Comment by FreakyAli** [comment]
@ExLuzZziVo try with the latest pre-release you should be able to do it!

**Comment by ExLuzZziVo** [comment]
@FreakyAli On the latest pre-release version it still returns the empty collection. Also I think this collection should be immutable, like Array.

**Comment by FreakyAli** [comment]
@ExLuzZziVo Can you suggest what you need here, with an example maybe?

**Comment by ExLuzZziVo** [comment]
@FreakyAli, The `IBiometric.GetEnrolledBiometricTypesAsync()` method returns a list, which is not immutable collection. The return type should be i.e. BiometricType[] because it will not be changed anymore. This change is just for a good code style.
