### ISSUE TITLE
Android force set Negative text, Ignore value in AllowPasswordAuth 

### ISSUE THREAD

**Issue by jvicius** [FreakyAli/Plugin.Maui.Biometric#13]
Plugin throw error in Android for Negative Text, i set AllowPasswordAuth = false, but the error continues.

var authenticationRequest = new AuthenticationRequest
{
    AllowPasswordAuth = false, // A chance to fallback to password auth
    Title = "RoofHub", // On iOS only the title is relevant, everything else is unused. 
    Subtitle = "",
    Description = Services.Localization.GetValue("EnableBiometrics_Enable"),
    AuthStrength = AuthenticatorStrength.Strong // Only relevant on Android
};

**Comment by FreakyAli** [comment]
did you check the error message that is thrown?

**Comment by FreakyAli** [comment]
@jvicius Did you get a chance to update this?

**Comment by jvicius** [comment]
> @jvicius do you have any update on this?

Hello, Yes for work i set in both cases the negative text.

**Comment by FreakyAli** [comment]
@jvicius so it's working? If yes could you close this?
