### ISSUE TITLE
How to protect an app after resume?

### ISSUE THREAD

**Issue by erossini** [FreakyAli/Plugin.Maui.Biometric#15]
I'm using your control in my `.NET 8 MAUI` application. I like to know how to use it when the app is sent in the background and how to resume.

If I add in my App.xaml.cs_

```csharp
protected override async void OnResume()
{
    base.OnResume();

    var isAvailable = await CrossFingerprint.Current.IsAvailableAsync(true);

    if (isAvailable)
    {
        var request = new AuthenticationRequestConfiguration("Login using biometrics", 
                                      "Confirm login with your biometrics");
        request.AllowAlternativeAuthentication = true;

        var result = await CrossFingerprint.Current.AuthenticateAsync(request);

        Console.Write(result);
    }
}
```

the application always shows the dialog for the authentication without allows the user to use the app. How can I ask the user to authenticate before continuing using the app?

Thank you in advance,
Enrico

**Comment by FreakyAli** [comment]
I am guessing you are not using this plugin

**Comment by FreakyAli** [comment]
@erossini have you by mistake raised this in the wrong plugin sir?

**Comment by FreakyAli** [comment]
Closing because this has no response, please reopen if needed
