### ISSUE TITLE
iOS Fingerprint issue

### ISSUE THREAD

**Issue by dlange-h3ko** [FreakyAli/Plugin.Maui.Biometric#16]
I tested the Biometric authentication with an iPhone 7 and have fingerprint activated.

In your code you simply responded with **Enrolled**, when there is no FaceID used. Here it does not matter if I am using "Weak" as option. 
=> Reference to the class: https://github.com/FreakyAli/Plugin.Maui.Biometric/blob/a906545f1dc43fc702510a7b2dc2a7e2212b2d0c/Plugin.Maui.Biometric/Plugin.Maui.Biometric/Platforms/iOS/BiometricService.ios.cs#L15

Is there a reason or is it a bug?

**Comment by dlange-h3ko** [comment]
Update: Seems to be fixed in an open PR => https://github.com/FreakyAli/Plugin.Maui.Biometric/pull/11

**Comment by FreakyAli** [comment]
I will be releasing this soon, since I am busy for Atleast this week you will have to wait a little for this, thanks for the understanding!
