### ISSUE TITLE
First Authentication Attempt Fails to Launch Fingerprint Scan Prompt

### ISSUE THREAD

**Issue by HelloooJoe** [FreakyAli/Plugin.Maui.Biometric#18]
**Description:**  
I'm encountering an issue when trying to authenticate using fingerprint biometrics on my app via `_biometricService.AuthenticateAsync()`. On the first attempt, the biometric prompt fails, and I receive an error. However, if I call the authentication function again, it works as expected.

### Steps to Reproduce:
1. Set up the biometric authentication using the `Plugin.Maui.Biometric` plugin in a .NET MAUI app targeting **.NET 8.0**.
2. Deploy the app on a **Samsung SM-G973U (Android 12, API 31)**.
3. Call the authentication function to trigger biometric authentication.

### Expected Behavior:
The fingerprint prompt should appear and allow the user to authenticate successfully on the first attempt.

### Actual Behavior:
On the first call to the authentication function, the biometric prompt doesn't appear, and I get an error. If I try again immediately after, the authentication succeeds.

### Code Snippet:
```csharp
public async Task<Response<CreateAccessTokenResponse>> AuthenticationUserAsync()
{
    // Check if biometric data is enrolled on the device
    var enrolled = await _biometricService.GetEnrolledBiometricTypesAsync();
    if (!enrolled.Any())
        return new Response<CreateAccessTokenResponse>
        {
            ErrorMessage = "You must have biometric data enrolled on your device to use this feature"
        };

    // Check if biometric authentication is available on the device
    var authenticationStatus = await _biometricService.GetAuthenticationStatusAsync();
    if (authenticationStatus != BiometricHwStatus.Success)
        return new Response<CreateAccessTokenResponse>
        {
            ErrorMessage = "Biometric authentication is not available on this device"
        };

    // Authenticate the user
    var authenticationResponse = await _biometricService.AuthenticateAsync(new AuthenticationRequest
    {
        AllowPasswordAuth = false,
        Title = "Fingerprint sign in",
        Subtitle = "Sign in using your fingerprint scan.",
        NegativeText = "Cancel",
        Description = "Touch the fingerprint sensor",
        AuthStrength = AuthenticatorStrength.Strong
    }, CancellationToken.None);

    // Check if the authentication was successful
    if (authenticationResponse.Status == BiometricResponseStatus.Failure)
        return new Response<CreateAccessTokenResponse>
        {
            ErrorMessage = "Biometric authentication failed"
        };

    // Return the access token
    return new Response<CreateAccessTokenResponse>
    {
        Data = new CreateAccessTokenResponse
        {
            AccessToken = "access_token_placeholder",
            RefreshToken = "refresh_token_placeholder",
        }
    };
}
```

### Device Info:
- **Device**: Samsung SM-G973U
- **Android Version**: 12
- **API Level**: 31
- **Framework**: .NET MAUI 8.0

### Additional Notes:
- The issue only happens on the first authentication attempt. Once I retry, the biometric prompt shows up and works fine.
- There are no specific error messages indicating what went wrong, just the absence of the fingerprint prompt.

Please let me know if you need further details or steps to help troubleshoot the issue.

**Comment by FreakyAli** [comment]
> Please let me know if you need further details or steps to help troubleshoot the issue.

Is there an exception that is thrown did you check if there is. 

There is also a property in the response that gives you error details did you check that?

Are you sure you are on UIThread when you call the `AuthenticateAsync` method

**Comment by FreakyAli** [comment]
Instead of `MainThread.InvokeOnMainThread` use `Application.Current.Dispatcher.DispatchAsync` 

And please close this if your issue is fixed!

**Comment by HelloooJoe** [comment]
The issue has been resolved by using `Application.Current.Dispatcher.DispatchAsync` in the service implementing `AuthenticateAsync`
