### ISSUE TITLE
Hide the "Enter Password" button and "Enter your password" label in the system iOS popup when the `AllowPasswordAuth` is set to `false`

### ISSUE THREAD

**Issue by pavelliolia** [FreakyAli/Plugin.Maui.Biometric#19]
The `AuthenticateAsync` method accepts the `AllowPasswordAuth` flag as part of the `AuthenticationRequest`. The flag is set to `false` by default, or can be explicitly set to `false`. It means that the user cannot use the iPhone passcode.

The issue is that the system biometric popups in iOS still contain the "Enter Password" button and "Enter your password" label.
![face-id-not-recognized-popup](https://github.com/user-attachments/assets/35e10c49-22b8-40b3-bcc7-9bb1696d03b2)
(ignore the "Sign in with biometric" label - it is set in my app)
![touch-id-not-recognized-popup](https://github.com/user-attachments/assets/47af2c65-adc2-4753-875d-ef0fb16f4ff9)

A quick research shows that we need to explicitly set the `localizedFallbackTitle` to an empty string in order to omit them.
https://stackoverflow.com/questions/28103575/how-to-remove-enter-password-and-cancel-button-from-touch-id-alert-view

So looks like we need to do something like this [here](https://github.com/FreakyAli/Plugin.Maui.Biometric/blob/master/Plugin.Maui.Biometric/Plugin.Maui.Biometric/Platforms/iOS/BiometricService.ios.cs#L32):
```csharp
var context = new LAContext();
if (request.AllowPasswordAuth is false)
{
    context.LocalizedFallbackTitle = string.Empty;
}
```

**Comment by pavelliolia** [comment]
@FreakyAli I would be happy to create a pull request with the fix if you wish.
For now, I forked your library and did that change there. Tested it with my app and it works.

**Comment by FreakyAli** [comment]
Feel free to raise a PR, I will check it over the weekend! ✌️

**Comment by FreakyAli** [comment]
@pavelliolia Can you check this with v0.0.4-pre?
